String YOUR_SUPABASE_URL = "https://gienbzcsmyedlkdwtzrp.supabase.co";
String YOUR_SUPABASE_ANON_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZW5iemNzbXllZGxrZHd0enJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDU4MDgyOTksImV4cCI6MTk2MTM4NDI5OX0.ZAk2Y59dtFeI85CPDkisq-af-QwKTlWNKAf7E5-P1pw";
